/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tplabo3_ejercicio2_conversordetemp;

import javax.swing.JOptionPane;

/**
 *
 * @author jeso_
 */
public class ConversorDeTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversorDeTemperatura
     */
    public ConversorDeTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        JPPanelTrasero = new javax.swing.JPanel();
        JLConversorDeTemperatura = new javax.swing.JLabel();
        JLIngreseTemperatura = new javax.swing.JLabel();
        JBBotonTransformador = new javax.swing.JButton();
        JTCajaDeGrados = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de grados Farenheit");
        setBackground(new java.awt.Color(153, 153, 0));

        JPPanelTrasero.setBackground(new java.awt.Color(0, 153, 153));

        JLConversorDeTemperatura.setBackground(new java.awt.Color(51, 204, 255));
        JLConversorDeTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLConversorDeTemperatura.setText("Conversor de temperatura:");
        JLConversorDeTemperatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        JLConversorDeTemperatura.setOpaque(true);

        JLIngreseTemperatura.setText("Ingrese una temperatura en grados Celsius");

        JBBotonTransformador.setText("Convertir a FARENHEIT");
        JBBotonTransformador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBBotonTransformador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBotonTransformadorActionPerformed(evt);
            }
        });

        JTCajaDeGrados.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        JTCajaDeGrados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTCajaDeGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTCajaDeGradosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPPanelTraseroLayout = new javax.swing.GroupLayout(JPPanelTrasero);
        JPPanelTrasero.setLayout(JPPanelTraseroLayout);
        JPPanelTraseroLayout.setHorizontalGroup(
            JPPanelTraseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPanelTraseroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLConversorDeTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPanelTraseroLayout.createSequentialGroup()
                .addGap(0, 198, Short.MAX_VALUE)
                .addComponent(JLIngreseTemperatura)
                .addGap(196, 196, 196))
            .addGroup(JPPanelTraseroLayout.createSequentialGroup()
                .addGroup(JPPanelTraseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPanelTraseroLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(JBBotonTransformador, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPPanelTraseroLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(JTCajaDeGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPPanelTraseroLayout.setVerticalGroup(
            JPPanelTraseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPanelTraseroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JLConversorDeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(JLIngreseTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTCajaDeGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBBotonTransformador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPanelTrasero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPanelTrasero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBBotonTransformadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBotonTransformadorActionPerformed
         try {
            int gradosCelsius = Integer.parseInt(JTCajaDeGrados.getText());
            double gradosFahrenheit = (9.0 / 5.0 * gradosCelsius) + 32;
            JOptionPane.showMessageDialog(this, "La temperatura en grados Fahrenheit es de: " + gradosFahrenheit);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        }
    }//GEN-LAST:event_JBBotonTransformadorActionPerformed

    private void JTCajaDeGradosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCajaDeGradosKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            // Ejecutar la acción del botón al presionar Enter
            JBBotonTransformadorActionPerformed(null);
        }
    }//GEN-LAST:event_JTCajaDeGradosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorDeTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBotonTransformador;
    private javax.swing.JLabel JLConversorDeTemperatura;
    private javax.swing.JLabel JLIngreseTemperatura;
    private javax.swing.JPanel JPPanelTrasero;
    private javax.swing.JTextField JTCajaDeGrados;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
