/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tplabo5_ejercicioagenda.Vistas;

import java.util.TreeMap;
import javax.swing.JOptionPane;
import tplabo5_ejercicioagenda.Contactos;

/**
 *
 * @author jeso_
 */
public class AgendaTelefonicaVista extends javax.swing.JFrame {
        TreeMap<Long, Contactos> Agenda;
    /**
     * Creates new form AgendaTelefonicaVista
     */
    public AgendaTelefonicaVista() {
        initComponents();
        Agenda = new TreeMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();
        JLformularioDeContacto = new javax.swing.JLabel();
        JLdni = new javax.swing.JLabel();
        JTdni = new javax.swing.JTextField();
        JTnombre = new javax.swing.JTextField();
        JLnombre = new javax.swing.JLabel();
        JTapellido = new javax.swing.JTextField();
        JLapellido = new javax.swing.JLabel();
        JTdireccion = new javax.swing.JTextField();
        JLdireccion = new javax.swing.JLabel();
        JTciudad = new javax.swing.JTextField();
        JLciudad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JTtelefono = new javax.swing.JTextField();
        JLtelefono = new javax.swing.JLabel();
        JBbuscar = new javax.swing.JButton();
        JBnuevo = new javax.swing.JButton();
        JBguardar = new javax.swing.JButton();
        JBborrar = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 51, 51));

        JLformularioDeContacto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        JLformularioDeContacto.setForeground(new java.awt.Color(255, 234, 58));
        JLformularioDeContacto.setText("Formulario de Contacto");

        JLdni.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLdni.setForeground(new java.awt.Color(255, 255, 255));
        JLdni.setText("DNI:");

        JTdni.setBackground(new java.awt.Color(0, 0, 0));
        JTdni.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTdni.setForeground(new java.awt.Color(255, 255, 255));
        JTdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTdniFocusLost(evt);
            }
        });

        JTnombre.setBackground(new java.awt.Color(0, 0, 0));
        JTnombre.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTnombre.setForeground(new java.awt.Color(255, 255, 255));
        JTnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTnombreFocusLost(evt);
            }
        });

        JLnombre.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLnombre.setForeground(new java.awt.Color(255, 255, 255));
        JLnombre.setText("Nombre:");

        JTapellido.setBackground(new java.awt.Color(0, 0, 0));
        JTapellido.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTapellido.setForeground(new java.awt.Color(255, 255, 255));
        JTapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTapellidoFocusLost(evt);
            }
        });

        JLapellido.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLapellido.setForeground(new java.awt.Color(255, 255, 255));
        JLapellido.setText("Apellido:");

        JTdireccion.setBackground(new java.awt.Color(0, 0, 0));
        JTdireccion.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTdireccion.setForeground(new java.awt.Color(255, 255, 255));

        JLdireccion.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLdireccion.setForeground(new java.awt.Color(255, 255, 255));
        JLdireccion.setText("Direccion:");

        JTciudad.setBackground(new java.awt.Color(0, 0, 0));
        JTciudad.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTciudad.setForeground(new java.awt.Color(255, 255, 255));
        JTciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTciudadFocusLost(evt);
            }
        });

        JLciudad.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLciudad.setForeground(new java.awt.Color(255, 255, 255));
        JLciudad.setText("Ciudad:");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        JTtelefono.setBackground(new java.awt.Color(0, 0, 0));
        JTtelefono.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        JTtelefono.setForeground(new java.awt.Color(255, 255, 255));
        JTtelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTtelefonoFocusLost(evt);
            }
        });
        JTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtelefonoActionPerformed(evt);
            }
        });

        JLtelefono.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        JLtelefono.setForeground(new java.awt.Color(255, 255, 255));
        JLtelefono.setText("Telefono:");

        JBbuscar.setBackground(new java.awt.Color(0, 0, 0));
        JBbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBbuscar.setForeground(new java.awt.Color(255, 255, 255));
        JBbuscar.setText("Buscar");
        JBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBbuscarActionPerformed(evt);
            }
        });

        JBnuevo.setBackground(new java.awt.Color(0, 0, 0));
        JBnuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBnuevo.setForeground(new java.awt.Color(255, 255, 255));
        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBguardar.setBackground(new java.awt.Color(0, 0, 0));
        JBguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBguardar.setForeground(new java.awt.Color(255, 255, 255));
        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBborrar.setBackground(new java.awt.Color(0, 0, 0));
        JBborrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBborrar.setForeground(new java.awt.Color(255, 255, 255));
        JBborrar.setText("Borrar");
        JBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBborrarActionPerformed(evt);
            }
        });

        JBsalir.setBackground(new java.awt.Color(0, 0, 0));
        JBsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBsalir.setForeground(new java.awt.Color(255, 255, 255));
        JBsalir.setText("Salir");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(JLtelefono)
                                .addGap(18, 18, 18)
                                .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(escritorioLayout.createSequentialGroup()
                                    .addComponent(JLdni)
                                    .addGap(40, 40, 40)
                                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(JBbuscar))
                                        .addComponent(JLformularioDeContacto)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JBnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(JBguardar)
                        .addGap(18, 18, 18)
                        .addComponent(JBborrar)
                        .addGap(18, 18, 18)
                        .addComponent(JBsalir))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JLapellido)
                                    .addComponent(JLnombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTapellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTdni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLdireccion)
                                    .addComponent(JLciudad))
                                .addGap(18, 18, 18)
                                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(JLformularioDeContacto)
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLdni)
                    .addComponent(JTdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBbuscar))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnombre)
                    .addComponent(JTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLapellido)
                    .addComponent(JTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLdireccion)
                    .addComponent(JTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLciudad)
                    .addComponent(JTciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLtelefono)
                    .addComponent(JTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBnuevo)
                    .addComponent(JBguardar)
                    .addComponent(JBborrar)
                    .addComponent(JBsalir))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtelefonoActionPerformed

    private void JTdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTdniFocusLost
        if (JTdni.getText() == null || JTdni.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Recuerde ingresar el DNI");
    } else {
        try {
            long dni = Long.parseLong(JTdni.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El DNI debe ser un número válido.");
    }
}
    }//GEN-LAST:event_JTdniFocusLost

    private void JTnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTnombreFocusLost
        String nombre = JTnombre.getText();
        
        if (nombre.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "El campo no debe contener números. Por favor, ingrese un nombre válido.");
        } 
    }//GEN-LAST:event_JTnombreFocusLost

    private void JTapellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTapellidoFocusLost
        String apellido = JTnombre.getText();
        
        if (apellido.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "El campo no debe contener números. Por favor, ingrese un nombre válido.");
        } 
    }//GEN-LAST:event_JTapellidoFocusLost

    private void JTciudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTciudadFocusLost
        String ciudad = JTnombre.getText();
        
        if (ciudad.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "El campo no debe contener números. Por favor, ingrese un nombre válido.");
        } 
    }//GEN-LAST:event_JTciudadFocusLost

    private void JTtelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTtelefonoFocusLost
       try {
            long telefono = Long.parseLong(JTtelefono.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El telefono debe ser un número válido.");
    }
    }//GEN-LAST:event_JTtelefonoFocusLost

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        JTdni.setText("");
        JTnombre.setText("");        
        JTapellido.setText("");
        JTdireccion.setText("");
        JTciudad.setText("");
        JTtelefono.setText("");        
    }//GEN-LAST:event_JBnuevoActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        long dni = Long.parseLong(JTdni.getText());
        String nombre = JTnombre.getText();
        String apellido = JTapellido.getText();
        String direccion = JTdireccion.getText();
        String ciudad = JTciudad.getText();
        long telefono = Long.parseLong(JTtelefono.getText());
        
        Contactos c1 = new Contactos(dni, nombre, apellido, ciudad, direccion);
        Agenda.put(telefono, c1);
        JOptionPane.showMessageDialog(null, "El contacto " + nombre + " se guardo con exito en la agenda!");
        
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBborrarActionPerformed
        long telefono = Long.parseLong(JTtelefono.getText());
        try {
            Agenda.remove(telefono);
            JOptionPane.showMessageDialog(null, "El numero fue removido de la agenda.");
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "No se borro el numero de telefono correctamente");
        }
    }//GEN-LAST:event_JBborrarActionPerformed

    private void JBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBbuscarActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        BuscarTelefono a2 = new BuscarTelefono();
        a2.setVisible(true);
        escritorio.add(a2);
    }//GEN-LAST:event_JBbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaTelefonicaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaTelefonicaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaTelefonicaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaTelefonicaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaTelefonicaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBborrar;
    private javax.swing.JButton JBbuscar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLapellido;
    private javax.swing.JLabel JLciudad;
    private javax.swing.JLabel JLdireccion;
    private javax.swing.JLabel JLdni;
    private javax.swing.JLabel JLformularioDeContacto;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JTextField JTapellido;
    private javax.swing.JTextField JTciudad;
    private javax.swing.JTextField JTdireccion;
    private javax.swing.JTextField JTdni;
    private javax.swing.JTextField JTnombre;
    private javax.swing.JTextField JTtelefono;
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
